# Assignment_1
If you copy codes from previous answers, explain each step. No explanation is `0 points`.

##  Part 1.Data types


a.Declare one variable for each one these types: : int , float , string , boolean.
- Print  the varible's type using  type () function




In [1]:
mi_entero = 10          # int
mi_decimal = 3.14       # float
mi_cadena = "Hola"      # string
mi_booleano = True      # boolean

# Imprimir el tipo de cada variable
print(type(mi_entero))
print(type(mi_decimal))
print(type(mi_cadena))
print(type(mi_booleano))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


 b. Using only the following inputs: ```5``` and ```2```  ,  work the  operators to get the output  : ```50```

In [9]:
# Usando solo 5 y 2 para obtener 50
resultado = (5 * 5) *  2

# Imprimir el resultado
print(resultado)

50


c. Evaluate if the output of the previous excercise is over 100. Create a variable that makes this evaluation. (Hint: It would be a boolean).

In [11]:
# Evaluar si el resultado es mayor a 100
es_mayor_que_100 = resultado > 100

# Imprimir el resultado de la evaluación
print(es_mayor_que_100)

False


d. Create a variable equal to a list that contains: 
- a string,
- a boolean,
- two numeric values ( of any kind)  and
- a  list of two strings with the names of your favourite musical artists. 

In [3]:
mi_lista = [
    "Hola, Daniel :)",  # Un string
    0.000001 > 0,           # Un booleano
    42,             # Un número entero (int)
    3.14159,           # Un número decimal (float)
    ["Radiohead", "Lana del Rey"]  # Lista con dos nombres de artistas musicales
]

# Imprimir la lista
print(mi_lista)

['Hola, Daniel :)', True, 42, 3.14159, ['Radiohead', 'Lana del Rey']]


## Part 2. Containers

e. Create a tuple with 3 elements. Explain why you can't modify it. 

In [1]:
Tupla_grupo7 = (2022, 2023, 2024)
Tupla_grupo7

#No se puede modificar porque la función de las tuplas consiste en almacenar datos de manera inmutable. 

(2022, 2023, 2024)

f.Create a dictionary with at least 3 different  keys and values .

In [5]:
diccionario_integrantes = {"Integrante_1":"Juan Calzado", "Integrante_2":"Pablo Torres", "Integrante_3":"Renzo Zevallos"}

In [7]:
diccionario_integrantes

{'Integrante_1': 'Juan Calzado',
 'Integrante_2': 'Pablo Torres',
 'Integrante_3': 'Renzo Zevallos'}

g.We got the next courses list: 

In [133]:
courses = ["History", "Economy", "Anthropology", "Sociology", "Literature"]

g.1.Add tree additional courses in 3 different ways( one for each way):
   - Sum (+) a list that contains an additional course. 
   - Use append. 
   - Use extend. 

In [136]:
#Sum (+) a list that contains an additional course. 
extra_course = ["Qlab - RStudio for Social Science"]
courses = courses + extra_course
print(courses)

['History', 'Economy', 'Anthropology', 'Sociology', 'Literature', 'Qlab - RStudio for Social Science']


In [138]:
#Use append
courses.append("Qlab - Python")
print(courses)

['History', 'Economy', 'Anthropology', 'Sociology', 'Literature', 'Qlab - RStudio for Social Science', 'Qlab - Python']


In [140]:
#Use extend
courses.extend("Qlab - Python: Time series")
print(courses)

['History', 'Economy', 'Anthropology', 'Sociology', 'Literature', 'Qlab - RStudio for Social Science', 'Qlab - Python', 'Q', 'l', 'a', 'b', ' ', '-', ' ', 'P', 'y', 't', 'h', 'o', 'n', ':', ' ', 'T', 'i', 'm', 'e', ' ', 's', 'e', 'r', 'i', 'e', 's']


g.2.Use the indexation to stress _Sociology_.

In [143]:
courses.index("Sociology")
print(courses[3])

Sociology


g.3 Remove your least favourite course

In [146]:
courses.remove("Sociology")
print(courses)

['History', 'Economy', 'Anthropology', 'Literature', 'Qlab - RStudio for Social Science', 'Qlab - Python', 'Q', 'l', 'a', 'b', ' ', '-', ' ', 'P', 'y', 't', 'h', 'o', 'n', ':', ' ', 'T', 'i', 'm', 'e', ' ', 's', 'e', 'r', 'i', 'e', 's']


g.4. Invert the list

In [149]:
courses.reverse()
print(courses)

['s', 'e', 'i', 'r', 'e', 's', ' ', 'e', 'm', 'i', 'T', ' ', ':', 'n', 'o', 'h', 't', 'y', 'P', ' ', '-', ' ', 'b', 'a', 'l', 'Q', 'Qlab - Python', 'Qlab - RStudio for Social Science', 'Literature', 'Anthropology', 'Economy', 'History']


h.Create a dictionary that representst a fruits inventory:
 - Add at least 5 fruits to the inventory
- Print the amount of apples in stock 
- Modify the amount of grapes


In [153]:
frutas_cantidad = { "apples":5, "grapes":24, "pineaplles":3, "watermelon":1, "oranges":4}
print(frutas_cantidad)

{'apples': 5, 'grapes': 24, 'pineaplles': 3, 'watermelon': 1, 'oranges': 4}


In [155]:
#Cantidad de manzanas:
frutas_cantidad["apples"]

5

In [165]:
#Aumento de la cantidad de uvas:
frutas_cantidad.update( {"grapes":48} )
print(frutas_cantidad["grapes"])

48


i.  Write a dictionary with the local GMT of the nexts cities:
- Antananarivo, Madagascar, 
- Beirut, Lebanon, 
- Jakarta, Indonesia, 
- Teherán, Iran, 
- Vientiane, Laos, 



Hint: Lima would be: `"Lima": -5`

In [184]:
local_GMT = {"Antananarivo, Madagascar":"+3", "Beirut, Lebanon":"+2", "Jakarta, Indonesia":"+7", "Teherán, Iran":"+3:30", "Vientiane, Laos":"+7"}
print(local_GMT)

{'Antananarivo, Madagascar': '+3', 'Beirut, Lebanon': '+2', 'Jakarta, Indonesia': '+7', 'Teherán, Iran': '+3:30', 'Vientiane, Laos': '+7'}


 j.Add the nexts cities to the dictionary:
- Astana, Kazakhstan,
- Uagadugú, Burkina Faso,
- Balmopan, Belize

In [187]:
local_GMT.update( {"Astana, Kazakhstan":"+6", "Uagadugú, Burkina Faso":"0", "Balmopan, Belize":"-6"} )
print(local_GMT)

{'Antananarivo, Madagascar': '+3', 'Beirut, Lebanon': '+2', 'Jakarta, Indonesia': '+7', 'Teherán, Iran': '+3:30', 'Vientiane, Laos': '+7', 'Astana, Kazakhstan': '+6', 'Uagadugú, Burkina Faso': '0', 'Balmopan, Belize': '-6'}


# Part 3. Numpy


k.Create an array with 10 aleatory values that go from 0 to 9

In [16]:
import numpy as np
valores=np.random.randint(0,10,size=10)
print(valores)

[1 9 2 2 4 7 1 7 5 6]


l.Create a matrix 3x2 fill with zeros

In [18]:
import numpy as np
matrix=np.zeros((3, 2))
print(matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


m.Sum two arrays and then multiply the output by an scalar

import numpy as np
valores_1=np.random.randint(0,10,size=10)
valores_2=np.arange(10)
valores_3= valores_1+valores_2
print(valores_3)
escalar=2
multiplicacion=valores_3*escalar
print(multiplicacion)


n.Create 2 arrays with the values that you wish :
- Concatenate vertically 
- Concatenate horizontally 

In [22]:
valor_1=np.ones((3, 3))
valor_2=np.ones((3, 3))
valor_3=np.vstack((valor_1, valor_2))
print(valor_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
